name: 'CI test'

inputs:
  system-name:
    required: true

#From https://docs.github.com/en/actions/guides/publishing-docker-images

runs:
  using: "composite"
  runs-on: ubuntu-latest
  permissions:
    contents: read
    packages: write

  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - uses: satackey/action-docker-layer-caching@v0.0.11
      # Ignore the failure of a step and avoid terminating the job.
      continue-on-error: true
      # Cache across the same system
      with:
        key: ${{ system-name }}-docker-cache-{hash}
        restore-keys: |
          ${{ system-name }}-docker-cache-

    - name: Add write permission to directories
      run: |
        find . -type d -exec chmod 777 {} \;

    - name: Setup ${{ system-name }} system
      run: |
        make sys_${{ system-name }}
