name: 'CI test'

inputs:
  system-name:
    required: true

#From https://docs.github.com/en/actions/guides/publishing-docker-images

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - uses: satackey/action-docker-layer-caching@v0.0.11
      # Ignore the failure of a step and avoid terminating the job.
      continue-on-error: true

    - name: Add write permission to directories
      shell: bash
      run: |
        find . -type d -exec chmod 777 {} \;

    - name: Setup some system
      shell: bash
      run: |
        make sys_eff
