name: Simple badges
on:
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  badge_job:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - id: date
        run: echo "##[set-output name=data;]$(date)"
      - name: Time badge
        uses: RubbaBoy/BYOB@v1.2.1
        with:
          NAME: time
          LABEL: 'Updated at'
          STATUS: ${{ steps.date.outputs.data }}
          COLOR: 00EEFF
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}